# Generated by Django 3.2 on 2021-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bool_field',
            field=models.BooleanField(default=True),
        ),
    ]
