# Generated by Django 3.2 on 2021-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_post_bool_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bool_field',
            new_name='reading_type_professional',
        ),
    ]
