# Generated by Django 3.2 on 2021-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_rename_bool_field_post_reading_type_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer_type',
            field=models.TextField(null=True),
        ),
    ]
