# Generated by Django 3.2 on 2021-05-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_post_float_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='float_field',
        ),
    ]
