# Generated by Django 3.2 on 2021-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_remove_post_float_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(null=True),
        ),
    ]
