# Generated by Django 3.2 on 2021-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_post_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='float_field',
            field=models.FloatField(null=True),
        ),
    ]
